

services:
  web:
    build: .
    container_name: apotek-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: apotek
      DB_USER: postgres
      DB_PASS: admin

  db:
    image: postgres:15
    container_name: apotek-db
    restart: always
    environment:
      POSTGRES_DB: apotek
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./web/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: apotek-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  dbdata:
  pgadmin_data:
